/**
 * Resume/CV template created with Bootstrap 5 by @vmoratog and @jdnichollsc
 */
const resume = {
  window:'Estiven Taborda',
  firstName: 'Estiven',
  lastName: 'Taborda',
  jobTitle: 'Mechanical Engineer',
  city: 'Medellín',
  postalCode: '',
  country: 'Colombia', 
  phone: '+573226696950',
  email: 'etabordah@gmail.com',
  t_education:'Education',
  education: [
    {
      school: 'Universidad Nacional de Colombia Sede Medellín',
      degree: "Bachelor's Degree",
      graduationDate: '2022',
      description: 'Mecanical Engineer'
    }
  ],
  t_links:'Links',
  links: [
    {
      label: 'GitHub',
      link: 'https://github.com/etabordah'
    },
    {
      label: 'LinkedIn',
      link: 'https://www.linkedin.com/in/etabordah/'
    },
  ],
  t_skills: 'Skills',
  skills: [
    'Programming Languages: Python, C++.',
    'Relevant Libraries: Pandas, OpenCV, FastAPI, matplotlib, GCP Apis, TensorFlow.',
    'Data Analysis Tools: SQL, LookerStudio, LookerML, Excel.'
  ],
  t_languages:'Languages',
  languages: ['English', 'Spanish'],
  t_aboutme:'Profile',
  professionalSummary: 
    "Passionate about Data Science, I make data available and analyze it in a way that drives business decisions in the fields of Maintenance and Operations.\nI analyze patterns and create models to extract value from data generated by the Internet of Things (IoT) devices that I design and connect to the Data Lake.\nAs a Product Owner, I can precisely identify stakeholders' needs and facilitate execution using Agile Methodologies.",
  t_workexp:'Work Experience',
  employmentHistory: [
    {
      jobTitle: 'Consultant',
      startDate: 'July 2021',
      endDate: 'Present',
      employer: 'Mantum S.A.S.',
      city: 'Medellin, Col',
      achievements: [
        'Created connectors for Looker Studio Data Studio, enabling the development of custom BI insights and dashboards for clients.',
        'Modeled insights and dashboards from databases using REST APIs and SQL.',
        'Analyzed data to provide valuable insights, helping customers make informed decisions.',
        'Guided maintenance and operations executives in implementing TPM, RCM, and RBM methodologies to improve performance.',
        'Utilized Excel and Python for data preprocessing.',
        'Managed projects as a Product Owner using Agile methodologies (SCRUM and Kanban) with Azure DevOps.',
        'Gathered, defined, and prioritized product requirements, created detailed user stories, and acceptance criteria, and maintained the product backlog.',
        'Developed web automation solutions using Python, Selenium, and FastAPI.',
        'Automated administrative processes and document generation using Python, AppsScript, and Google Calendar API.',
        'Supported the management and development of IoT projects where more than 400 devices were installed throughout the country.',
        'Programmed and developed the mechanical and electrical design of IoT devices as well as managed their manufacturing.',
        'Developed an app for coordinating and documenting IoT installations, including automatic generation of delivery certificates.'
      ]
    },
    {
      jobTitle: 'Co-Founder y CEO',
      startDate: 'September 2019',
      endDate: 'June 2021',
      employer: 'Latincueros',
      city: 'Medellin, Col',
      achievements: [
        'Performed financial analysis to make strategic decisions.',
        'Design and execute commercial strategies.',
        'Developed applications for accounting, production, and operations.',
        'Created software for measuring leather areas using computer vision techniques.'
    ]
    }
  ],
  photo: 'profile.jpg',
}

const formatResume = (r) => ({
  ...r,
  address: [
    r.country,
    r.city,
    r.postalCode
  ].filter(Boolean).join(', ')
})

new Vue({
  el: "#app",
  data: formatResume(resume)
});

/**
 * Wait for animatable-component to be loaded (Only for VanillaJS)
 **/
function animatableLoaded() {
  document.querySelector('body').classList.remove('d-none');
}
if (customElements) {
  customElements.whenDefined('animatable-component').then(animatableLoaded);
} else animatableLoaded()